### ISSUE TITLE
Maven, tests

### ISSUE THREAD

**Issue by Suntrie** [mishkowsky/ConsoleUtility#1]
<s>1. Пока структура папок не соответствует структуре папок Maven проекта (приходится выставлять alias-ы sources root/ test sources root вручную средствами Идеи). Посмотреть на то, как оно должно быть, чтобы подхватываться автоматически можно, например, [здесь](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) ;</s> **Upd.** Пока что-то пошло не так с sources directory
![image](https://user-images.githubusercontent.com/31803067/112897819-c103db80-90e8-11eb-81e9-b1238b463511.png)

<s>2. Для хранения тестовых файлов следует использовать соответствующую папку resources в тестах, про нее можно посмотреть по той же ссылке + (здесь)[https://mkyong.com/java/java-read-a-file-from-resources-folder/] ;</s> **Upd.** Просьба попробовать использовать для чтения ресурсов предназначенные для этого специальные методы (см. ссылку). Для тестов это может быть менее актуально, но с ресурсами аналогичным образом работают и из основного кода. От файлов в "рандомной папке" они отличаются тем, что попадают, например, в состав jar-файла и их не надо отдельно носить за собой. Относительный же путь будет работать только в случае запуска из [рабочей директории](https://www.jetbrains.com/help/idea/2017.1/run-debug-configuration-maven.html?utm_medium=help_link&utm_source=from_product&utm_campaign=IC&utm_content=2017.1#parameters) и существования связанной иерархии папок по относительному пути
<img width="1440" alt="Screenshot 2021-03-29 at 23 53 10" src="https://user-images.githubusercontent.com/31803067/112898773-ef35eb00-90e9-11eb-860d-49782edf1981.png">  - можно поставить эксперимент - посмотреть, что один input.txt копируется в classes (содержимое которого будет kinda соответствовать содержимому jar-файла, которое в него попадет из Вашего проекта), другой лежит в рабочей директории -> изменить содержимое в рабочей директории и увидеть, что тесты упадут. 

<s>3. Про относительные пути - у меня сейчас тестовый файл на Unix-е, например, не найдется - проблема такая же, как с разделителями строк внутри файла - в зависимости от ОС они разные. Хорошая новость: при необходимости использовать относительный путь, можно скопировать средствами Идеи: правой кнопкой мыши по файлу-> Copy relative path from content root - получите путь в стиле Unix, он универсален для различных ОС;</s>

4. Пока тест падает (очевидно, зависит от языка системы), трассировать системные (не кастомизированные) сообщения - не очень хорошая идея:
`Expected :someFile.txt (Не удается найти указанный файл)
Actual   :someFile.txt (No such file or directory)`

5. А Вам точно в зависимостях нужна 
`   <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
        </dependency>`?

6.  Будьте, пожалуйста, готовы обсудить назначение assembly/maven-jar.

**Comment by Suntrie** [comment]
Это все аналогично второй части проекта + просьба проверить тестовое покрытие.

**Comment by mishkowsky** [comment]
assembly/maven-jar упаковывает проект в jar со всеми библиотеками, указанными в <dependencies> ("толстый" jar, jar-with-dependencies), а также самостоятельно включает в сборку MANIFEST.MF, при использовании тега <manifest>.
maven-jar-plugin упаковывает проект в jar, но без всех необходимых библиотек.
